# Example config showing the default values.

# Set this to change what port the server binds to
#Port = 8080

# Set the ListenHost to change what host you want the server to listen on.
# For example, setting it to 127.0.0.1 would make it accept only connections
# from localhost, and 0.0.0.0 would accept all incoming connections.
#ListenHost = "127.0.0.1"

# The WikiDir is where your markdown files will be stored.
#WikiDir = "./wiki/"

# Enable ServeStatic to allow the server to serve static files...
# (html, js, css, images, etc.)
#ServeStatic = true

# If you have ServeStatic enabled, this will be your static file server's
# document root.
#Webroot = "./wwwroot/"

# Create the search index in memory? Setting to tru will use more memory, but
# will have higher performance
#IndexInMemory = false

# If you choose not to hold the search index in memory, this is where the index
# will reside on disk.
#IndexLoc = "./pages.index"

# In your static file server, if the static file doesn't exist, this file will
# be served instead of a 404 response. This is handy for serving single page
# apps. If you don't set a file name, the 404 response will be given. This path
# should be relative to the webroot folder.
#
# This setting does nothing if ServeStatic is false.
#DefaultFile = ""

# Sanitize the HTML output when rendering markdown files? If enabled, you will
# not get syntax highlighting in code blocks.
#SanitizeHTML = true